version: '2'
services:
  "webapp-digitopia":
    container_name: webapp-digitopia
    build:
      context: ../
      dockerfile: docker-assets/Dockerfile-webapp
    ports:
      - "3000:3000"
    env_file:
      - ../localdev.env
    networks:
      - frontend

  "nginx-digitopia":
    container_name: nginx-digitopia
    restart: always
    build:
      context: ../
      dockerfile: docker-assets/Dockerfile-nginx
    ports:
      - "8080:8080"
    networks:
      - frontend

networks:
  frontend:
